//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocrataClocks.Controls {
    
    
    public partial class Clock {
        
        /// <summary>
        /// HourSpinner control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SocrataClocks.Controls.HourSpinner HourSpinner;
        
        /// <summary>
        /// MinuteSpinner control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SocrataClocks.Controls.MinuteSpinner MinuteSpinner;
        
        /// <summary>
        /// AMPMSpinner control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SocrataClocks.Controls.AMPMSpinner AMPMSpinner;
    }
}
